# Generated by Django 4.2.1 on 2023-05-11 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shippingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
