# Generated by Django 4.2.1 on 2023-05-15 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_cart_user_alter_orders_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.datetime(2023, 5, 16, 0, 15, 55, 18015))),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='purchases.cart')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
