# Generated by Django 4.2.1 on 2023-05-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_wishlist_saveditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavedItem',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
