# Generated by Django 4.2.1 on 2023-05-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_remove_wishlist_user_delete_saveditem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
